coverage:
  status:
    # only stat pull request
    patch:
      default:
        ## need patch coverage higher than 70% then success
        target: 70%
        ## allow the coverage rate decline 10%
        threshold: 10%
  ## full coverage should more than 50%
  range:
    50..100
## ignore packages
ignore:
  - scripts
  - examples
  # generated proto
  - vm/proto
  # generated contracts
  - smartcontracts
  # test utils
  - test
  - testutil
  # e2e test
  - cmd/e2etest
  - cmd/stresstest
  # metrics
  - metrics
  # main
  - cmd/coordinator/main.go
  - cmd/prover/main.go
  - cmd/sequencer/main.go
  - project/project_easyjson.go
  - persistence/contract/contract_easyjson.go
  - persistence/contract/project_easyjson.go
  - persistence/contract/prover_easyjson.go
