[package]
name = "halo2-ponseidon-circuit"
version = "0.1.0"
edition = "2021"

[dependencies]
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v2023_04_20", features = ["dev-graph"]}
halo2_curves = { git = "https://github.com/privacy-scaling-explorations/halo2curves", tag = "0.3.2", package = "halo2curves" }
snark_verifier = { git = "https://github.com/privacy-scaling-explorations/snark-verifier.git", rev="fedd7a8", package = "snark-verifier" }
rand = "0.8.5"
itertools = "0.11.0"
hex = "0.4.3"
plotters = { version = "0.3.0", default-features = true }
wasm-bindgen = "0.2.87"
getrandom = { version = "0.2", features = ["js"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
clap = { version = "4.4.11", features = ["derive"] }

# eigentrust-zk = {git = "https://github.com/Liuhaai/zk-eigentrust"}
eth-types = {git = "https://github.com/privacy-scaling-explorations/zkevm-circuits", default-features = false}
primitive-types = "0.12.2"
num-bigint = { version = "0.4.0", features = ["rand"] }
num-integer = "0.1.42"
num-traits = "0.2.11"
num-rational = "0.4.1"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
