// Code generated by MockGen. DO NOT EDIT.
// Source: ../../output/output.go
//
// Generated by this command:
//
//	mockgen -write_generate_directive -package=mock -destination=./mock_output.go -source=../../output/output.go
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	types "github.com/machinefi/sprout/types"
)

//go:generate mockgen -write_generate_directive -package=mock -destination=./mock_output.go -source=../../output/output.go

// MockOutput is a mock of Output interface.
type MockOutput struct {
	ctrl     *gomock.Controller
	recorder *MockOutputMockRecorder
}

// MockOutputMockRecorder is the mock recorder for MockOutput.
type MockOutputMockRecorder struct {
	mock *MockOutput
}

// NewMockOutput creates a new mock instance.
func NewMockOutput(ctrl *gomock.Controller) *MockOutput {
	mock := &MockOutput{ctrl: ctrl}
	mock.recorder = &MockOutputMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutput) EXPECT() *MockOutputMockRecorder {
	return m.recorder
}

// Output mocks base method.
func (m *MockOutput) Output(task *types.Task, proof []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Output", task, proof)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Output indicates an expected call of Output.
func (mr *MockOutputMockRecorder) Output(task, proof any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Output", reflect.TypeOf((*MockOutput)(nil).Output), task, proof)
}

// Type mocks base method.
func (m *MockOutput) Type() types.Output {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(types.Output)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockOutputMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockOutput)(nil).Type))
}
