name: pr_check

on:
  push:
    branches: [ "develop", "pull-request" ]
  pull_request:
    branches: [ "develop", "pull-request" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Run Unit tests.
        # skip integration testing
        run: go test -p 1 -gcflags="all=-N -l" `go list ./... | grep -v github.com/machinefi/sprout/cmd/tests` -covermode=atomic -coverprofile cover.out

      - name: Setup Docker and Colima
        if: startsWith(matrix.os, 'macos-latest') == true
        run: |
          brew install docker colima
          colima start

      - name: Run Integration tests.
        run: make integration_test

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./cover.out
