name: Codecov
on:
  push:
    branches: [ "develop", "pull-request" ]
  pull_request:
    branches: [ "develop", "pull-request" ]

jobs:

  test:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.21

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run Unit tests.
        run: go test ./... -coverprofile cover.out -covermode=atomic

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./cover.out

  #build:
  #  name: Build
  #  runs-on: ubuntu-latest
  #  needs: [lint, test]
  #  steps:
  #    - name: Set up Go
  #      uses: actions/setup-go@v1
  #      with:
  #        go-version: 1.12

  #    - name: Check out code
  #      uses: actions/checkout@v1

  #    - name: Build
  #      run: make build